Annexe I: De la comptabilité de propriété privée à la comptabilité des biens communs (par Bob Haugen) 
Le système de comptabilité en partie double est apparu au début du capitalisme marchand et a été l'une des institutions qui ont aidé le capitalisme à se fondre dans un système au lieu d'individus isolés.
L '«équation comptable» à double entrée est
Actif = passif + capitaux propres
Ou, en bref, «ALOE».
En d'autres termes, le modèle ALOE comprend la comptabilité du point de vue d'un propriétaire de capital.
Évolution de la comptabilité
Le système comptable Resource-Event-Agent [REA] est né du développement de bases de données relationnelles informatisées dans les années 1970, lorsque la duplication d'un système papier à double entrée dans une telle base de données violait les règles de «normalisation» relationnelle: l'élimination des doubles entrées rend le base de données plus simple et peut fournir les mêmes rapports financiers. Bill McCarthy, qui a fait le travail de simplification, visait le plus petit nombre de concepts pouvant faire le travail1.
La première version de REA était encore un système de comptabilité interne pour une entreprise individuelle. En tant que tel, il n'a pas eu beaucoup de succès en dehors du milieu universitaire, où il était utilisé pour enseigner la logique sous-jacente à la comptabilité. Mais pour les opérations commerciales, il ne présentait pas suffisamment d'avantages pour justifier l'évolution des systèmes et des pratiques comptables.
Cependant, le développement de systèmes ERP (Enterprise Resource Planning) sur des bases de données relationnelles a commencé à ressembler beaucoup plus à REA qu'à ALOE, en partie parce qu'ils normalisaient également leurs bases de données. Les systèmes ERP ne faisaient généralement pas de doubles saisies, sauf pour les générer automatiquement pour un système ALOE qui ressemblait plus à un module complémentaire pour satisfaire les comptables qu'à un composant essentiel pour gérer l'entreprise.
La vision indépendante de REA est née du développement des systèmes de chaîne d'approvisionnement dans les années 1990. Dans une chaîne d'approvisionnement, les entreprises individuelles importent beaucoup moins que le flux de ressources de la queue à la tête de la chaîne. Les doubles entrées du point de vue d'une entreprise ne font que brouiller l'image. Si chaque entreprise de la chaîne tente de capter plus que sa part de valeur, elle affaiblit toute la chaîne. (Ce qui arrive souvent…)
En outre, les chaînes d'approvisionnement ont commencé à ressembler davantage à des partenariats qu'à des commerçants indépendants achetant sur un «marché libre» par prix. Les constructeurs automobiles distribuent leurs nomenclatures (et plus) à leurs fournisseurs et se réunissent dans une organisation dont la «mission est de permettre la collaboration au sein des industries automobiles et connexes». Apple investit dans ses fournisseurs. Toyota souhaite un flux monobloc ininterrompu des fournisseurs au produit final. Les écosystèmes commerciaux commencent à être conceptualisés et gérés consciemment: plus collaboratifs que les chaînes d'approvisionnement. En 2014, Forbes déclare que «l'écosystème des entreprises» est le prochain grand mot à la mode.
Cela a amené les modèles sémantiques partagés tels que REA (mais pas toujours exactement REA) au premier plan du développement de logiciels de chaîne d'approvisionnement et d'écosystème d'entreprise. (Compte tenu de l'évolution des relations commerciales, quelque chose comme REA devait émerger, et plus d'une chose comme REA l'a fait.) Les blockchains commencent maintenant à codifier ces modèles sémantiques partagés. Un comité de normalisation ISO est en train de rédiger une norme de blockchain, et des experts REA font partie du comité.
La vision indépendante de REA enregistre les événements économiques au fur et à mesure qu'ils se produisent, enregistrant les agents impliqués, sans interprétation comptable du point de vue d'un seul agent, «le propriétaire». Sur la base des enregistrements d'événements économiques de base, de nombreuses interprétations sont possibles.
Répercussions
Les événements économiques qui impliquent des externalités telles que les déchets et la pollution devront également être enregistrés, ainsi que la consommation ou la dégradation de toutes les autres ressources qui ne sont pas désormais sous la «propriété» comme le microbiote de l'air, de l'eau et du sol. Ces enregistrements peuvent être interprétés à la lumière de la biocapacité et de la santé des écosystèmes.
Une interprétation utile est sous la forme de graphiques de flux de ressources, qui peuvent être à la fois visualisés et calculés mathématiquement: par exemple, en utilisant une analyse entrées-sorties. Voici un exemple de graphique de flux de ressources qui a été utilisé pour analyser les pêches en Nouvelle-Écosse:

Ici, nous pouvons voir la comparaison de deux ensembles différents de méthodes de pêche, Otter Trawl (gros chalutiers commerciaux qui grattent tout le lit de pêche) vs Trap, Palangre et Handline (méthodes durables à faible impact pour petits bateaux), et leurs effets sur Terrains de pêche.
Résumé des systèmes comptables
L'ALOE, basée sur la propriété du capital, n'a pas de sens pour un système comptable axé sur les communs, contrairement à la vision indépendante REA des événements économiques et des flux de ressources. 
Implémentations de la vue indépendante REA dans un logiciel orienté P2P
Le système de planification des exigences de réseau [NRP] a été développé dans le cadre d'une collaboration entre Sensorica et Mikorizal, en utilisant la vision indépendante de REA. NRP est à ERP comme la vision indépendante de REA est à ALOE: prendre le point de vue des réseaux plutôt que d'une seule entreprise.
Le PNR favorise la garde des ressources plutôt que la propriété, où les agents de conservation sont responsables de la garde des ressources communes mais n'ont pas de droits de propriété comme la capacité de vendre les ressources. Les ventes de ressources sont déléguées par le réseau à des «sociétés d'échange» de confiance. La frontière entre les agents producteurs et les firmes d'échange génère une membrane semi-perméable, qui permet la création de valeur marchande à partir de ressources communes.
De plus, le PNR ne traite pas les personnes en tant qu'employés. Ce sont tous des agents libres. Ils peuvent se voir offrir des opportunités de contribuer, mais ils ne peuvent rien faire.
Open Collaborative Platform [OCP] de FreedomCoop et le logiciel LearnDeep pour leur réseau de fab lab de lycée à Milwaukee Wisconsin USA sont des fourchettes du NRP. Freedom Coop est un projet créé par FairCoop qui veut créer un système économique «intégral» complet en Europe. OCP a commencé comme une plate-forme pour Freedom Coop, mais s'est élargi pour incorporer plusieurs autres projets Fair Coop, y compris la Banque des Communes. OCP a ajouté plusieurs fonctionnalités à NRP, y compris des connexions à leur crypto-monnaie FairCoin et à sa blockchain Fair Chain. Fair Chain a un mécanisme de consensus différent de Bitcoin ou Ethereum, appelé «preuve de coopération», qui utilise des «nœuds validés en collaboration» (CVN) pour créer de nouveaux blocs.
LearnDeep veut «recycler» les matériaux donnés par les entreprises locales et les utiliser pour les créations de fab lab d'étudiants. Ils ajoutent des «inventaires ouverts» au PNR, où les fab labs de différentes écoles de la région de Milwaukee peuvent voir quels matériaux sont disponibles dans toutes les autres écoles et auprès des donateurs et les demander et les déplacer d'une école à une autre en utilisant les systèmes de transport de la bibliothèque. Ils utiliseront également la fonction de recette NRP pour partager des conceptions et des méthodes, et parleront à Sensorica à l'automne pour explorer les possibilités de collaboration en matière de conception. Fair Coop prévoit également d'utiliser des inventaires ouverts entre ses «nœuds locaux» et utilisera les mêmes fonctionnalités logicielles.
Locecon, le logiciel d'analyse économique locale, était basé sur le même modèle que NRP, mais porté à un niveau supérieur, avec des agrégats d'agents et de ressources, pour analyser les flux potentiels et réels de ressources au sein d'une communauté.
Les réseaux d'entraide (un projet pour organiser des économies locales coopératives) utilisent Locecon pour l'analyse et prévoient de l'utiliser dans une boucle de rétroaction entre l'analyse et les niveaux opérationnels, où les événements réels du réseau alimentent l'analyse, puis de nouveau comme suggestions d'amélioration des projets opérationnels.
Stade actuel de la pratique
NRP et toutes ses fourchettes, ainsi que Locecon, sont des preuves de concept de travail plutôt que les systèmes nécessaires à l'économie de coordination mutuelle de l'avenir. Ce sont des expériences. Ils fonctionnent et sont utilisés dans la pratique dans les organisations qui ont créé les fourches. Mais ils ne sont pas adaptés d'un point de vue architectural à une économie de coordination mutuelle à grande échelle. Architecturalement, ce sont des plates-formes: c'est-à-dire que tous les participants utilisent le même code, le même serveur et la même base de données.
Étape suivante
L'étape suivante des expériences des mêmes personnes qui ont développé les preuves de concept consiste à refactoriser ces systèmes en composants plus petits qui peuvent être déployés sur des infrastructures décentralisées. Bien que les composants puissent être utilisés sur des blockchains, nous ne les considérons pas comme décentralisés ou suffisamment flexibles pour les besoins à venir, qui, selon nous, impliqueront de nombreux agents de toutes sortes, à la fois des individus et des organisations, partout dans le monde, dans de nombreux domaines. , et ont besoin de contributions créatives de la part de nombreuses personnes qui doivent être capables d'agir de manière indépendante tout en étant capables d'interopérer. Les blockchains sont comme des plateformes dans la mesure où tous les participants utilisent le même code et la même blockchain logique, bien que la chaîne puisse avoir de nombreux réplicants.
Nous pensons donc que l'avenir doit être construit sur des vocabulaires et des protocoles plutôt que sur des plates-formes, voire des plates-formes coopératives. Cela se produit dans plusieurs projets, par exemple, l'Open Cooperative Ecosystem (OCE) émergeant de FairCoop.
Le vocabulaire pour les réseaux économiques de coordination mutuelle est en cours d'élaboration dans le projet ValueFlows, qui a émergé de plusieurs projets antérieurs, y compris NRP, et utilise l'ontologie REA comme base.
ValueFlows a commencé à définir la suite de composants requise. Le projet OCE développe actuellement certaines des applications. FairCoop utilise maintenant la première application Agent. Les réseaux d'entraide se penchent sur l'OCE et collaborent aux premières étapes de développement avec des membres de FairCoop.
Les participants à l'OCE testent trois protocoles décentralisés différents: Scuttlebutt, Holochain et ActivityPub. La communauté Moinho au Brésil travaille avec Scuttlebutt; FairCoop et les réseaux d'entraide travaillent avec ActivityPub; et le projet Holochain ne fait que commencer maintenant, avec quelques implémentations primaires d'exemples de devises de crédit mutuel crypto, qui sont une étape vers l'intégration REA. Le but ultime est de faire fonctionner les composants sur les trois protocoles et de pouvoir communiquer avec chacun d'eux. Chacun de ces protocoles a des avantages et des inconvénients, et sera plus utile dans certaines situations, mais peut-être pas aussi utile dans d'autres. Et puis, le temps et la pratique le diront.
