  
Chapitre 2: Outils et technologies pour des écosystèmes de production intégrés, équitables et durables
introduction 
Nous assistons à la surface d'un large éventail d'outils et de pratiques numériques pertinents pour représenter la valeur des interactions sociales et économiques. Divers groupes sociaux ont commencé à organiser leurs efforts pour exploiter les opportunités des infrastructures technologiques partagées, en investissant leur propre vision et leurs ambitions dans leur développement.
Dans ce chapitre, nous fournissons un bref aperçu des principales technologies habilitantes et de quelques outils exemplaires qui investissent dans ce potentiel. Nous nous concentrons principalement sur différentes solutions complémentaires permettant de représenter les externalités sociales et environnementales. Ces externalités, tant positives que négatives, sont largement invisibles dans les médias comptables actuels, qui reconnaissent presque exclusivement les transactions médiées par les prix. En revanche, nous avons maintenant des capacités technologiques et sociales croissantes pour tenir compte d'une réalité économique plus pluraliste, socialement et écologiquement intégrée.
Notre cartographie est structurée en trois couches:
    • Une couche d'intégration mutuelle, où des registres distribués et des chaînes d'approvisionnement partagées1 sont utilisés pour faciliter les flux d'informations et de connaissances dans les communautés productives afin de permettre et d'orienter les contributions. En généralisant les informations sur l'état actuel des choses et les agents dans un écosystème, la forme de coordination stigmergique qui détermine la PPCB dans les biens immatériels peut passer à la production physique.
    • Une couche de mécanismes de circulation et d'échange qui procurent et allouent la coopération humaine nécessaire, ainsi que les ressources matérielles et énergétiques. L'utilisation de signaux alternatifs (qu'ils soient monétaires ou non) peut coordonner et surveiller les relations d'entrée et de sortie en intégrant les résultats sociaux et environnementaux souhaités.
    • Une couche de cadres de planification des seuils et allocations globaux permet la gestion des flux de matière et d'énergie et assure la responsabilité de biocapacité des acteurs de ces réseaux. Le cadre de planification peut également être utilisé pour orienter les ressources vers les priorités sociétales (Donut Economics de Kate Raworth est un bon cadre pour examiner l'interaction de ces deux facettes).
Le reste de ce chapitre décrit les outils d'intégration mutuelle, suivis des outils de circulation et d'échange. Les cadres de comptabilité et de planification spécifiques seront examinés au chapitre 3.
La distinction entre les trois couches ci-dessus ou les différentes fonctions des outils n'est pas toujours simple. Il existe en fait un vaste domaine de chevauchement et de complémentarité entre les différents outils et leurs technologies sous-jacentes, ainsi que les principes et objectifs sous-tendant leur conception. De plus, notre description concerne largement les intentions conceptuelles des différents outils et n'est pas limitée par une faisabilité technologique donnée à l'heure actuelle. En termes simples, notre intention principale est d'illustrer ce qui est à la fois possible et souhaitable dans la manière dont nous orientons la conception des technologies qui définiraient largement les institutions collectives des sociétés futures.
Les données pertinentes proviennent des différentes descriptions des projets à travers leurs propres médias populaires, mais aussi de la documentation juridique et opérationnelle interne, le cas échéant. Par conséquent, la description représente la vision d'un projet que les instigateurs eux-mêmes veulent communiquer sur leur projet, interprété avec un regard critique par les auteurs. Néanmoins, l'objectif est d'illustrer la vision populaire pour elle-même et d'identifier les tendances et les modèles d'interprétation, plutôt que de représenter un ensemble empirique de preuves pour un certain nombre de solutions technologiques.
Ce que nous faisons spécifiquement dans les deux prochains chapitres, c'est de nous poser la question: comment pouvons-nous modifier et transformer la vague actuelle de technologie de grand livre distribué basée sur la blockchain, avec ses prémisses libertaires, anarcho-capitalistes et basées sur `` l'économie autrichienne '', alors que nous pouvons arriver à des technologies de grand livre plus compatibles avec un système de fabrication et de production socialement juste et écologiquement durable?
    • On peut imaginer par exemple, une conception de grand livre non centralisée, sans validation oligarchique: c'est ce qu'apporte Holochain.
    • Nous pouvons imaginer un ensemble de protocoles qui nous permettent de construire des sous-systèmes économiques centrés sur les communs, comme l'ECSA nous permettrait de le faire.
    • On pourrait imaginer remplacer les jeux compétitifs de la théorie des jeux, qui gouvernent désormais les schémas incitatifs des projets blockchain, par des «jeux coopératifs» comme R-Chain propose de le faire.
    • On pourrait imaginer remplacer les contrats intelligents, basés sur des accords individuels, par des contrats Ostrom, permettant des accords plus collectifs, basés sur les communs (Sustans).
    • On peut imaginer remplacer les devises basées sur l'offre et la demande spéculatives (devises matières premières), par des devises liées à des contributions humaines, basées sur un réseau de confiance (Trustlines), ou qui nous donnent des informations directes sur l'état écologique d'un ressource (devises adossées à des actifs telles que Fishcoin, Mangrove Coin, SolarCoin).

Outils d'intégration mutuelle 
Cette section est dédiée aux outils de base qui créent un environnement commun pour les acteurs d'un écosystème de production et de valeur, pour travailler ensemble et aligner leurs actions les unes sur les autres.
Les lecteurs techniques trouveront des détails dans les descriptions principales des outils sélectionnés, tandis que leur importance stratégique est mise en évidence dans un paragraphe d'introduction en caractères gras.
Ci-dessous, nous présentons les projets suivants impliqués dans de telles entreprises:
    • L'Agence spatiale économique (ECSA), qui développe un environnement pour les espaces économiques interconnectés et les organisations programmables distribuées basées sur les communs
    • Holochain, un registre distribué qui n'est pas une blockchain, et dont l'organisation est basée sur le biomimétisme, centré sur les personnes (agents) et leurs actions, permettant à quiconque d'interopérer des registres contextuels
    • DaoStack, qui construit des outils pour que les communautés productives puissent travailler les unes avec les autres, en utilisant des outils de gouvernance collective
En décrivant ces outils, nous ne revendiquons pas à ce stade leur pleine maturité technologique et leur exploitabilité, mais les projets ont tous été sélectionnés car ils ont effectivement démarré la production de leurs codages et infrastructures.
Agence spatiale économique (ECSA): Un environnement pour les espaces économiques interconnectés et les organisations programmables distribuées basées sur les communs
L'ECSA étend la notion d'organisation autonome distribuée à celle d'une organisation programmable distribuée (cDPO) basée sur les communs. Il veut créer les outils pour passer de la production coopérative de logiciels immatériels, c'est-à-dire étendre le paradigme open-source aux «espaces économiques open-source» basés sur les communs.
L'Agence spatiale économique (ECSA) est une organisation de recherche et développement dédiée aux solutions open-source qui peuvent permettre de nouvelles formes économiques. Sa mission phare actuelle envisage la création d'une pile technico-économique qui permettrait l'initiation, le financement et le fonctionnement des entités, ainsi que les conditions de leur coopération et interaction. La vision est centrée autour d'une plate-forme qui s'appuie sur la technologie du grand livre distribué pour soutenir un écosystème de projets et d'initiatives autonomes. Ces initiatives pourraient impliquer toutes sortes d'activités, des projets collaboratifs aux start-up et aux entreprises sociales, avec une orientation à but lucratif ou non lucratif, même des partis politiques et des groupes de réflexion. L'ECSA appelle ces «espaces économiques open source» et les considère comme une extension de l'économie open source. En substance, ECSA vise à déployer des contrats et des accords intelligents pour créer un ensemble de modèles cohérents parmi lesquels ces entités peuvent choisir. Il envisage une extension de la notion d'organisations autonomes distribuées aux «organisations programmables distribuées» basées sur les communs 2, réintégrant ainsi l'agence des organisations «autonomes» aux personnes concernées.
La pile ECSA comprend deux systèmes interdépendants, «Gravity» et «Space», soutenus par un service de conseil nommé «Accelerator». Gravity est une infrastructure distribuée qui fournit un protocole pour la création d'applications sécurisées par cryptographie. La gravité est décrite comme un World Computing Fabric, qui est une architecture modulaire permettant de créer des réseaux résilients et vérifiables de machines virtuelles (ECSA, 2018). Le World Computing Fabric évoque la critique de l'ECSA au modèle World Computer qui est caractéristique d'Ethereum, en raison de ses redondances et de ses limites pour les applications décentralisées. En revanche, Gravity offre plus de résilience et de flexibilité dans les réseaux d'ordinateurs décentralisés.
L'espace est un outil de développement logiciel modulaire qui facilite la création de programmes (semi) autonomes appelés «espaces économiques» 3. Il aspire à reproduire la socialité humaine et à permettre des formes intégrées de finance collective. Enfin, l'Accélérateur propose une large gamme de services d'accompagnement, allant de la conception, la création et la mise en œuvre d'espaces économiques à la recherche, l'organisation, la formation et l'exploitation du marché.
Les espaces économiques génèrent les ressources nécessaires pour les nouvelles entités économiques de l'écosystème ECSA en émettant des jetons fondés sur des actions. Les jetons sont personnalisés en fonction des valeurs et motivations intrinsèques de la communauté impliquée, et leur émission intègre les dispositions organisationnelles et opérationnelles souhaitées à un moment donné. L'équité des jetons peut représenter diverses formes de contributions pour divers groupes de parties prenantes, y compris des fonds, des compétences, une collaboration ou un savoir-faire.4
L'écosystème ECSA et les outils technologiques offrent une vision alternative de la finance, en permettant diverses formes d'investissements ou de contributions engagées dans la production réelle des initiatives concernées. En particulier pour les initiatives axées sur les communs, l'accès au financement est généralement restreint et les règles ne sont pas alignées sur les principes internes des communautés. Simultanément, le paysage de la blockchain a jusqu'à présent été dominé par des incitations spéculatives.
Les investisseurs ICO ne sont pas tellement intéressés par tout ce qui est produit par les nouvelles entreprises, mais spéculent principalement sur une augmentation potentielle du prix des crypto-jetons, afin de les vendre pour un profit rapide. L'ECSA franchit une étape importante pour contrer cette tendance, en reliant la valeur des jetons aux relations productives et à l'éthique interne des communautés qui les émettent. De plus, ils peuvent reconnaître différentes formes de contributions et en générer un enregistrement immuable pour guider l'interaction économique dans l'écosystème.

Holochain: une alternative à un grand livre distribué mondial, basé sur le biomimétisme
La principale raison pour laquelle le bitcoin et sa blockchain sont inefficaces en termes de consommation d'énergie est que chaque nouvelle transaction doit être validée par l'ensemble du réseau, ce qui entraîne une augmentation exponentielle du nombre de ressources nécessaires à la maintenance du système. Holochain fait cela de manière très différente. Ce n'est techniquement pas une blockchain, mais simplement un moyen pour des registres séparés de coopérer et de devenir interopérables les uns avec les autres. Par conséquent, Holochain est évolutif à l'infini au coût marginal.
Holochain signifie «stockage holographique pour les applications distribuées». Comme son nom l'indique, il s'agit d'un framework pour le développement et l'hébergement d'applications distribuées. Holochain peut être décrit comme une alternative à un registre distribué comportant une architecture nettement «plus légère». Au lieu de stocker une copie du registre entier sur chaque nœud du réseau et d'appliquer sa validation, Holochain adopte une approche centrée sur l'agent et divise les données en de nombreux nœuds différents et garantit l'accès uniquement aux données utiles ou pertinentes pour chaque nœud. . Cela signifie que chaque agent génère et conserve ses propres données sur son propre appareil. Les seuls types de données qui sont transférés vers - et sont lisibles par - d'autres agents sont ceux auxquels ils ont besoin d'accéder ou sont créés dans un «espace partagé».
Par la suite, l'intégrité des données dans Holochain est assurée grâce à un système de validation P2P. Cela n'implique pas de processus gourmands en ressources comme «l'extraction», ce qui permet à Holochain d'être plus facile à déployer sur des appareils moins puissants, tels que les téléphones mobiles. Holochain s'appuie plutôt sur ses pairs pour assurer l'intégrité des données partagées entre eux. Les pairs du réseau détiennent une partie des données et les valident par rapport à un ensemble de règles de validation partagées, qui sont spécifiques au protocole ou à une application (hApp). En d'autres termes, les utilisateurs vérifient les actions de chacun pour voir si elles ont été créées conformément à leurs règles de validation communes.
Les règles de validation peuvent varier selon les applications, car certaines peuvent exiger des règles plus strictes que d'autres. Par exemple, une crypto-monnaie peut avoir des règles de validation différentes de celles d'un réseau social. Par conséquent, les utilisateurs du système Holochain n'interagissent pas directement avec les données partagées entre les pairs du réseau. Toute interaction est plutôt effectuée à travers le code des applications, afin qu'elles appliquent leurs propres règles, restrictions et objectifs. Le concept même d'une application dans Holochain commence à s'effondrer. Grâce au niveau de composabilité des fonctionnalités et à cause du couplage lâche de l'interface utilisateur, l'écosystème évolue plutôt comme un ensemble de micro-services disposés dans des relations complexes les uns avec les autres, adaptés à l'utilisateur.
Tout comme Ethereum, Holochain a été développé pour prendre en charge la fonctionnalité des applications, sur la base d'accords entre les personnes qui les utilisent, des médias sociaux et des applications de messagerie à la gestion de la logistique partagée et aux crypto-monnaies. Dans l'ancien modèle client-serveur, l'existence d'un nœud central servait à maintenir l'intégrité des données et à assurer l'application des règles convenues. Avec les systèmes de grand livre distribués, ce nœud central est remplacé par un réseau de nœuds se synchronisant à un état commun. Holochain permet cette fonction sans avoir besoin d'un nœud central, auquel tout le monde est responsable et doit rendre compte. Il le fait en exigeant que chaque nœud accepte l'ensemble de règles partagé, le vérifie cryptographiquement avec une fonction de hachage comme entrée initiale dans son propre enregistrement,
Simultanément, il résout certains des principaux problèmes d'évolutivité associés à la technologie blockchain. Holochain n'exige pas que chaque nœud mette à jour une base de données unique détenue par tout le monde à chaque interaction du réseau. Au lieu de cela, les nœuds se valident mutuellement sur la base des informations qui sont mutuellement pertinentes et sur des règles spécifiques au contexte. De cette façon, le système devient plus efficace avec l'ajout de nouveaux nœuds, ce qui permet d'exploiter les effets de réseau.
En fin de compte, le type d'interaction activé par Holochain sera déterminé par les applications qui finiront par s'exécuter dessus. Cependant, nous ne suggérons pas que Holochain, comme en fait toute infrastructure technologique, soit neutre. Le Bitcoin, et dans une large mesure la plupart des infrastructures basées sur la blockchain, étaient imprégnés des principes qui étaient importants pour leurs concepteurs: l'anonymat, l'immuabilité et le contournement de la confiance humaine. À l'inverse, la conception d'Holochain présente plusieurs caractéristiques pertinentes pour les communs. Cela peut former la base d'une nouvelle réalité économique plus démocratique, plus inclusive, plus ouverte et mieux informée sur les seuils environnementaux locaux et mondiaux.
Plus spécifiquement, Holochain crée les conditions qui peuvent permettre à diverses entités économiques de mutualiser et de partager plus librement les ressources et de convenir de règles de conduite communes qui peuvent être appliquées de manière P2P. Cela peut permettre une répartition plus uniforme du pouvoir entre les agents participants et accroître la transparence. Holochain n'est pas à lui seul un protocole de coopération sociale, mais il peut soutenir la création et l'application de tels protocoles partagés. Combinées à la possibilité d'émettre et de distribuer des crypto-jetons, les communautés peuvent créer des systèmes de récompense plus équitables et de nouveaux médias pour s'interfacer avec le marché, tout en maintenant leur intégrité à leurs valeurs et principes. De plus, Holochain va au-delà des crypto-jetons, en permettant et en favorisant des formes de crypto-comptabilité à crédit mutuel, qui ont une capacité d'expression beaucoup plus grande que les jetons.
DAOstack: mécanismes intégrés pour une gouvernance à grande échelle
DAOstack est une plateforme décentralisée qui vise à faciliter l'auto-organisation des communautés productives en fournissant des outils d'auto-gouvernance collective. 
DAOstack, comme son nom l'indique déjà, fournit une pile d'outils technologiques pour le développement de DAO, comprenant: a) un cadre pour le déploiement de contrats intelligents sur la blockchain Ethereum (Arc); b) un environnement de développement frontal pour le développement d'applications décentralisées (Arc.js); et c) une interface utilisateur permettant le financement et l'allocation des ressources des organisations décentralisées (Alchemy). Ce dernier a été conçu de manière à permettre aux personnes sans connaissances techniques avancées d'interagir avec les autres couches du DAOstack, de lancer des DAO, d'émettre des crypto-jetons et d'inviter d'autres personnes à participer et à soutenir leurs idées.
La motivation principale de DAOstack est de fournir une infrastructure technologique à différentes organisations décentralisées, une infrastructure qui créerait un environnement collaboratif, accessible à une masse critique de personnes, pour lancer et participer. Il est souvent caractérisé par ses instigateurs comme un «Wordpress pour DAO. »5 De la même manière que Wordpress a permis à des personnes sans compétences de programmation préexistantes de gérer le contenu des sites Web, DAOstack envisage de faciliter la génération de DAO qui définissent les règles pour les organisations décentralisées.
De plus, les instigateurs de DAOstack aspirent à effectuer un équilibre fin entre l'évolutivité, c'est-à-dire le nombre de décisions qu'un collectif peut prendre dans une période de temps, et la résilience, c'est-à-dire l'incorruptibilité de ces décisions. A cet effet, un processus de prise de décision collective a été développé, appelé Consensus holographique. Ce processus repose sur de petits groupes de personnes qui prennent des décisions au nom de la plus grande majorité, mais d'une manière qui garantit un alignement parfait entre les deux groupes. Le consensus holographique permet des décisions plus rapides et localisées localement dans un DAO à grande échelle, en alignant les décisions locales sur l'opinion mondiale via un jeu crypto-économique. Essentiellement, un éventuel décalage entre les deux est présenté comme une opportunité économique, que les prédicteurs peuvent exploiter pour des gains économiques,
Instead of building a specific protocol to support different projects, DAOstack provides access to different layers for different sets of skills, so that diverse teams may develop their own protocols, based on their own values and principles. The coordination of these teams and their interaction with the rest of the DAOstack ecosystem is guided by the issuance and distribution of crypto-tokens — these function like price signals, i.e., as incentives for investments (of effort and energy); the difference is that there are different values co-encoded beyond simple supply and demand. Contributors of value to the network are rewarded with tokens, which in turn gain their value from the usability of the application offered. Subsequently, tokens may also be circulated among different decentralized organizations in the ecosystem to support or benefit from each other's services. 
De plus, DAOstack est lui-même un DAO qui émet son jeton natif (GEN). Cela sert à faciliter et à encourager la prise de décision collective sur le développement de l'écosystème DAOstack et l'accompagnement de nouveaux projets en plus et en parallèle. Un système d'attention et de récompense guide cette interaction, et cela se reflète dans la distribution des jetons GEN et de la réputation, qui se reflète également dans le pouvoir de vote.6
Le modèle de DAOstack fonctionne au-dessus de la blockchain Ethereum et il est donc sans doute contraint par les limitations qui y sont liées. En outre, le modèle du consensus holographique partage de nombreuses hypothèses de l'économie de marché libre, où les individus partagent une «rationalité» commune pour exploiter les opportunités de gains économiques et aligner efficacement l'offre et la demande mondiales. Mais la gouvernance est sans doute plus qu'un simple équilibre entre l'attention et les besoins de prise de décision. Cela nécessite des mécanismes collectifs, contraignants sur le plan éthique et sensibles à la valeur que la signalisation des marchés ne peut à elle seule réaliser.
Cependant, il offre une nouvelle perspective sur l'émission et la distribution de crypto-jetons, qui est orientée vers le soutien d'efforts collectifs et écosystémiques. Comme l'ECSA, il lie la valeur des jetons à la production réelle de produits et services utiles à partir d'une collaboration en réseau, permettant aux pairs de décider et d'appliquer leurs propres règles de coordination et de systèmes de récompense. Plus important encore, il offre une interface qui ouvre ces possibilités à un plus grand nombre de personnes qui n'ont pas forcément de compétences en programmation, ainsi qu'un système natif pour faciliter le lancement et l'accompagnement de nouvelles initiatives.
Outils de circulation et d'échange 
Cette section se concentre sur les outils de mise en œuvre de l'échange et de la distribution de «valeur».
Nous discutons des projets suivants:
    • FairCoin et FairCoop, un écosystème d'écosystèmes coopératifs ouverts d'échange de juste valeur
    • Envienta, qui développe un système de fabrication durable et open source intégré à l'échelle mondiale
    • FabChain est un projet de l'écosystème Fab Lab, visant à relier des Fab Labs spécifiques, à des systèmes de fabrication réels, pour lesquels ils fonctionnent comme des ressources collectives de R&D, en coopération avec les villes
    • Terra0, bien qu’au stade expérimental précoce, est basé sur le concept radical de donner une agence aux ressources naturelles, en les considérant comme des «DAO»

FairCoin et FairCoop: des outils pour un écosystème coopératif cosmo-local et ouvert
FairCoin, FairCoop et l'écosystème plus large dont il fait partie, visent à être un écosystème coopératif ouvert pour l'échange de valeur entre les communautés à la fois localement et à l'échelle mondiale. Elle est animée par les idées d'une «révolution intégrale» défendue par la coopérative catalane intégrale7 et est déjà utilisée par diverses communautés locales principalement en Espagne et en Grèce. C'est bien plus qu'une simple monnaie nouvelle et plus «juste», au sein d'un écosystème gouverné démocratiquement. Il vise plutôt à offrir une solution totale aux pratiques post-capitalistes.
FairCoin est une monnaie créée par FairCoop, l'écosystème coopératif ouvert mondial. La motivation derrière FairCoin a été la création d'un support de valeur pour le système économique FairCoop qui serait contrôlé par sa communauté mondiale. FairCoin a été lancé par un développeur anonyme qui a distribué gratuitement les 50 premiers millions d'unités aux personnes qui avaient manifesté leur intérêt, mais la monnaie a ensuite été acquise par le système FairCoop comme moyen de paiement.
Conformément aux valeurs de FairCoop, FairCoin repose sur le principe que la valeur est générée par la coopération, contrairement aux méthodes largement appliquées de frappe ou d'extraction qui génèrent et aggravent les inégalités dans la communauté des utilisateurs. La première version de FairCoin a expérimenté un protocole de consensus hybride entre la preuve de travail et la preuve de participation, visant un modèle plus écologique; quelques unités supplémentaires ont également été générées. Cependant, on s'est vite rendu compte qu'une approche complètement différente devait être développée.
Cela a conduit à la deuxième version de FairCoin, qui a implémenté un algorithme de consensus unique appelé preuve de coopération. Ce protocole n'est pas destiné à créer des unités supplémentaires, mais repose plutôt sur un réseau de nœuds à validation coopérative (CVN) de confiance pour valider les transactions et générer des blocs. Les opérateurs CNV sont désignés et approuvés par l'assemblée générale de FairCoop. Un nouveau bloc est créé toutes les trois minutes et le processus est coordonné entre les CVN par un système à tour de rôle. Un petit frais de transaction est facturé aux utilisateurs par le CVN qui génère un bloc à un moment donné, ce qui sert principalement à éviter les activités de spam et couvre également les coûts de fonctionnement du système.
La conception du système FairCoin lui permet de fonctionner efficacement avec de très faibles exigences en matière de traitement et de consommation d'énergie. FairCoop affirme qu'un réseau de jusqu'à 30 ordinateurs avec une capacité de traitement régulière suffit à couvrir son fonctionnement, nécessitant l'équivalent d'un ménage de 4 membres en consommation d'énergie annuelle.8 De plus, FairCoin est nettement moins sujet à la spéculation, liant ainsi sa valeur à véritable activité productive qui a lieu dans le système économique mondial FairCoop. Son taux de change est réglementé par des procédures démocratiques par l'assemblée générale de FairCoop, plutôt que par des opérations de libre-échange. Seule une petite fraction des FairCoins est détenue par des personnes qui ne sont pas directement impliquées dans FairCoop, tandis que la majorité des unités sont diffusées au sein d'une communauté de personnes partageant ses valeurs communes.
FairCoin est un cas très spécifique d'une monnaie qui a été créée pour servir un objectif spécifique par une communauté spécifique. Néanmoins, sa pertinence s'étend sans doute au-delà de l'écosystème FairCoop, étant un support de valeur explicitement conçu pour intégrer des règles de durabilité sociale et écologique. En outre, le fait qu'il soit basé sur le client bitcoin d'origine illustre de manière éloquente le potentiel de la technologie blockchain à permettre différents résultats socio-institutionnels, malgré ses fondements d'origine. Indépendamment de sa portée limitée, il montre comment la dynamique des petits groupes de communautés de confiance peut être mise à l'échelle au niveau mondial, facilitée par une infrastructure technologique qui incarne leurs valeurs et aspirations communes.
Trustlines: crédit mutuel pour le bien commun 
La plupart des crypto-monnaies sont des monnaies spéculatives `` matières premières '', dont la valeur dépend de l'offre et de la demande mais qui n'ont pas de relation directe avec les réalités matérielles durables, en d'autres termes, les signaux de prix ne donnent pas suffisamment d'informations sur l'utilisation durable des ressources représentées. Deux alternatives pour les devises sont, d'une part, les devises adossées à des actifs qui donnent des informations sur les stocks et les flux d'une ressource, afin qu'elle reflète une utilisation durable (Fishcoin, Mangrove Coin, SolarCoin). Les autres sont des monnaies de crédit mutuel qui, à notre avis, peuvent refléter des contributions humaines à des projets communs. Trustlines apporte une telle fonction de crédit mutuel dans l'environnement du grand livre distribué.

Trustlines9 est une plate-forme basée sur Ethereum qui permet l'émission d'IOU sur une base P2P. Son design s'inspire de l'idée originale du réseau de devises décentralisé «Ripple» (Fugger, 2004). Trustlines Network permet essentiellement aux utilisateurs de créer de l'argent en fournissant un crédit d'un montant qu'ils jugent équitable pour les personnes en qui ils ont confiance. Une Trustline est un contrat intelligent qui représente un accord entre deux personnes pour se connecter avec une ligne de crédit bilatérale. Ces lignes peuvent être traduites en pouvoir d'achat parmi les nœuds de confiance du réseau.
The Trustlines Network has no single native token. Money in the network can be denominated in fiat currencies, commodities, crypto-tokens or other units of account, based on rules agreed upon all the nodes participating in a certain network of trustlines denominated in the same form of currency. For instance, a credit line has been agreed between user A and user B. This credit can be directly translated into valid money for either user in their direct trustees. But, simultaneously, user A may also make a purchase from user C, provided that there is trust between users B and C. This relation may be further expanded as more users participate in the network and create trustlines between them. As long as a line of trust can be established, valid transactions can occur in the network. 
Le réseau Trustlines n'est pas très différent sur le plan fonctionnel de notre système monétaire actuel basé sur le crédit. L'argent est une forme de crédit qui devient valable pour toute personne qui fait confiance au créancier, qui est généralement un tiers de confiance, comme une banque centrale ou commerciale. En ce sens, Trustlines exploite les relations de confiance P2P pour permettre à n'importe qui de devenir créancier, dans des limites données. De plus, le système de crédit devient plus efficace10 à mesure qu'il évolue, en fonction d'utilisateurs bien connectés. Des frais minimes sont facturés sur chaque transaction et sont payés aux utilisateurs fournissant des connexions de confiance dans les transactions, incitant ainsi les utilisateurs à établir autant de connexions que possible.
Un aspect important de Trustlines est que les utilisateurs peuvent déterminer le niveau de crédit qu'ils accordent aux autres, en fonction de la façon dont ils se sentent à l'aise. Un équilibre convenu indique combien les utilisateurs se doivent entre eux et le pouvoir d'achat des utilisateurs est limité par cet équilibre. Par la suite, le réseau de toutes les lignes de confiance est géré par des contrats intelligents et fonctionne comme notaire pour toutes les lignes de crédit et tous les soldes. Dans le cas où un utilisateur ne peut pas rembourser sa dette, le litige est réglé en privé entre les parties concernées.
Les lignes de confiance, en tant que solution monétaire, présentent certes de nombreuses lacunes de notre système monétaire et comptable actuel fondé sur le crédit. De plus, dans la mesure où les crédits sont libellés en monnaie fiduciaire, il reste limité par la dynamique de pouvoir des institutions financières actuelles. Néanmoins, il présente toujours une application intéressante de la technologie blockchain pour permettre le crédit mutuel de manière P2P, basée sur des contrats intelligents appliquant des critères socialement déterminés. De cette façon, même si les relations de confiance réelles entre les gens deviennent abstraites à mesure que le réseau évolue, il est toujours possible d'appliquer et d'étendre les règles et valeurs convenues à leur réseau respectif. En outre, la possibilité d'utiliser différents types de fonds comme dénominateurs peut offrir un plus grand degré de flexibilité et de résilience dans le système,
Cercles: un revenu de base décentralisé
Circles est un projet coopératif développant un revenu de base P2P en utilisant la blockchain Ethereum. Il vise à explorer l'argent en tant que bien commun où les communautés peuvent gouverner le fonctionnement de la monnaie. Revenu de base «ascendant», Circles favorise la coopération et l'interaction économique en encourageant les réseaux commerciaux locaux. Plus les membres de la communauté sont connectés les uns aux autres, plus leur réseau devient précieux.

Circles est une monnaie sociale P2P dans laquelle les individus peuvent échanger un à un une fois qu'ils se font confiance dans le système. Ces relations forment un réseau de confiance, qui aide à protéger le système contre les attaques Sybil ou les personnes qui tentent de réclamer plus d'un revenu de base. Semblable aux lignes de confiance, la devise des cercles peut être échangée via une confiance transitive, dans laquelle les individus peuvent échanger avec n'importe qui dans les réseaux de confiance de l'autre. Les destinataires des cercles peuvent également valider leur devise auprès d'un intermédiaire afin d'étendre leur réseau de confiance.

Le système frappe un nombre égal de pièces Circles à tous les participants, comme un revenu de base universel. C'est une monnaie de surestaries, avec un taux de décroissance sur toutes les pièces émises, créant une économie résistante à la thésaurisation et post-accumulation. La politique monétaire de Circles est déterminée par un processus de gouvernance communautaire, engagé dans chaque hub régional de Circles. Les membres de la communauté s'entendent collectivement sur les paramètres du système tels que le taux d'émission, le taux de surestaries et les limites de confiance. Étant donné que la confiance humaine est une composante essentielle du système des cercles, le processus de gouvernance communautaire ne sera pas et n'est pas censé dépasser le niveau régional. Cela dit, une fois que plusieurs centres régionaux de cercles seront établis, il y aura probablement des occasions pour eux d'échanger et de se connecter.

Circles fonctionne via une série de contrats intelligents sur la blockchain Ethereum, mais il s'agit d'un protocole indépendant de la blockchain - et pourrait facilement fonctionner sur une autre chaîne, ou comme son propre protocole. Il existe une application mobile destinée aux utilisateurs pour iOS et Android, mais les jetons Circles peuvent également être consultés et interagis avec toute autre interface compatible ERC20. Enfin, pour une facilité d'utilisation et une faible latence, l'équipe Circles gère une série de services hors chaîne pour héberger des composants non critiques du système, tels que des photos de profil utilisateur et des transactions récentes mises en cache.

Le projet entreprendra un projet pilote de recherche à Berlin en 2019. L'objectif du projet pilote est de tester les hypothèses sur le système, y compris l'engagement des utilisateurs, et à ces fins, ils se sont associés à un collectif Radical Young Mothers, Prinzessinnengarten (un jardin communautaire et marché fermier) et Ola's Cafe, entre autres organisations. L'équipe lance également son propre café, Cafe Grundeinkommen, qui acceptera la monnaie et servira de centre communautaire pour la gouvernance des cercles. Enfin, l'application comprendra une fonction de «liste» permettant aux individus et aux organisations de publier des biens et services qu'ils sont prêts à échanger contre des cercles, favorisant ainsi un marché peer-to-peer.
Envienta: un environnement intégré pour la fabrication open-source
Envienta met en place un environnement intégré pour la fabrication open-source intégrée.
Envienta est une plate-forme visant à aider la conception ouverte et la fabrication distribuée. Sa vision est de fournir un cadre pour connecter les innovateurs, les créateurs et les concepteurs aux communautés de makerspace et éventuellement aux utilisateurs, aux consommateurs et aux chaînes d'approvisionnement existantes. Le framework Envienta est composé de: a) une plateforme, en tant qu'interface unique pour la gestion des comptes utilisateurs et des projets; b) un pôle d'innovation, cartographiant un réseau mondial de makerspaces et leurs capacités respectives; et c) un système éducatif orienté vers le partage de connaissances et de solutions dans un environnement facilité en ligne.
Tout utilisateur de l'écosystème Envienta peut lancer un projet et trouver des parties intéressées avec lesquelles collaborer. Après avoir formé une équipe et un plan initial, ils peuvent le diffuser sur le réseau afin d'attirer des investissements pour la conception et le prototypage de l'idée. Les prototypes sont ensuite partagés sous des licences Creative Commons, afin que d'autres puissent télécharger les plans, examiner, modifier et améliorer les produits, et les partager avec le reste du réseau. Enfin, une fois les produits arrivés à maturité, ils peuvent être introduits sur le marché via un réseau de fabricants, tandis que la plate-forme fournit une assistance sur les questions de marketing, juridiques et de propriété intellectuelle, conformément aux principes du CBPP.11
L'interaction dans l'écosystème Envienta est également facilitée par le crypto-jeton ENV, généré par le réseau Ethereum. Le jeton ENV sert à enregistrer et à gérer les flux de données dans l'écosystème, en donnant accès aux services produits, aux récompenses et à la réputation des contributeurs, tout en suivant les flux de valeur entre les projets et en soutenant le crowdsourcing interne.
L'objectif principal du système de jetons ENV est de renforcer la coopération au sein du réseau et de soutenir son modèle économique. Il permet aux agents de l'écosystème de décider des types de contributions et de ressources recherchées, tels que la main-d'œuvre, les énergies renouvelables, les terres, les outils et les machines, et de distribuer des récompenses en jetons ENV. Simultanément, la distribution de jetons est également liée aux droits de vote, tandis que la réputation reflète le pouvoir de vote. De plus, dans la mesure où ils représentent la valeur produite dans le réseau, ils peuvent également être diffusés hors du réseau pour engager des agents externes et acquérir des services.
En fin de compte, le système de jetons ENV envisage de prendre en charge un modèle économique basé sur les ressources. Il est compris comme une étape de transition vers une représentation d'un ensemble diversifié d'activités économiques, y compris l'innovation, la fabrication et les contributions, qui est étroitement liée aux ressources tangibles et immatérielles impliquées. Les jetons ENV aident à surveiller les flux de valeur entre les différentes parties prenantes et à créer un enregistrement en temps réel des moyens et des ressources disponibles.
À ses débuts, Envienta se concentre sur les domaines liés à la vie durable, à la domotique, à l'énergie verte et à la production alimentaire. Son approche est explicitement orientée vers la promotion de la durabilité et de la production économique basée sur les communs. Il s'inspire du concept de «cosmolocalisme» 12 (Ramos et al., 2017), qui s'appuie sur le potentiel de connaissances, d'informations et de design partagés au niveau mondial, en confluence avec la fabrication distribuée localisée, impliquant idéalement la mutualisation des outils technologiques et de installations. Le cosmo-localisme favorise une moralité partagée à travers les communs, dans le sens de co-créer et cogérer des ressources partagées.
FabChain: Lier la recherche avancée aux métabolismes urbains et à la production et à la fabrication traditionnelles
FabChain est idéalement positionné pour corréler les avancées de l'écosystème pionnier du Fab Lab, qui se concentre sur l'impression 3D et la fabrication relocalisée, en tant que laboratoires de R&D connectés à la fois à une ligue de villes engagées et à des organisations de fabrication.
FabChain13 est conçu comme un système basé sur des jetons pour résoudre les problèmes de fragmentation et de flux de valeur entre les capacités de conception et de fabrication locales distribuées et orientées vers les communs. Il s'appuie sur la communauté dynamique des Fab Labs, un réseau mondial de laboratoires de fabrication numérique comptant plus de 1300 membres et s'étendant dans plus de 100 pays. Simultanément, il fait avancer l'idée des Fab Cities, un concept mettant à l'échelle la culture du Fab Lab au niveau de la ville, promouvant un modèle de transformation urbaine basé sur l'utilisation durable des ressources et des matériaux locaux et le partage des cultures. L'importance spécifique de FabChain est qu'elle vise à connecter un réseau existant de laboratoires de recherche de pointe, avec une alliance de villes et avec les réseaux logistiques existants de l'industrie.
L'objectif principal de FabChain est d'impliquer les parties prenantes dans des pratiques de production d'économie circulaire durable et (open source), y compris le recyclage, la réutilisation et la relocalisation des chaînes d'approvisionnement au niveau de la ville, tout en permettant l'interaction et la synchronisation avec d'autres villes. Cela nécessiterait une infrastructure de chaîne de blocs confédérée qui pourrait faciliter l'allocation trans-locale des connaissances et des capacités de production, tout en surveillant les flux de matières dans les chaînes d'approvisionnement locales et transparentes. Dans ce processus, les makerspaces locaux joueraient un rôle déterminant dans la mobilisation et l'allocation des ressources matérielles et des moyens de production. Ces relations seraient convenues et appliquées par le biais de contrats intelligents qui garantiraient l'exécution automatique des conditions avec la distribution de jetons.
La conception des jetons FabChain encapsule diverses fonctions pour différentes parties prenantes de la chaîne d'approvisionnement. Ils peuvent fournir une certification; garantir la transparence et l'alignement sur les conditions éthiques (par exemple, commerce équitable, provenance, production biologique); stimuler la coopération et la synergie entre les différentes parties prenantes; encourager les activités économiques circulaires; distribuer des récompenses aux contributeurs; réglementer l'utilisation des ressources et des installations mutualisées; soutenir la pérennité du réseau en créant des liens avec l'économie de marché externe; encourager la participation; et établir une prise de décision fondée sur la réputation.
Le modèle de jeton de FabChain est destiné à offrir deux types différents de jetons: a) un jeton de réputation non transférable (FabRep); et b) un jeton utilitaire transférable (FabCoin). Le jeton de réputation représentera la valeur qu'un agent, que ce soit un individu, un groupe ou une organisation, a contribué au réseau, telle qu'elle est perçue au sein de leurs communautés respectives. Chaque communauté est autorisée à déterminer ses propres règles pour attribuer la réputation, car elle affecte également les relations de pouvoir dans sa prise de décision.
Les FabCoins peuvent être transférés entre les entités de l'écosystème pour récompenser ou encourager les contributions, promouvoir la production localisée et encourager la collaboration entre différents acteurs. En outre, différents acteurs peuvent fournir des produits et services en échange de FabCoins ou d'une autre devise. La valeur des jetons reflétera leur utilisabilité dans ces relations et leur reconnaissance en tant que mécanisme de réciprocité. En principe, les FabCoins pourraient être utilisés pour la rémunération des contributions dans le réseau, dans la mesure où ils donnent accès à des services utiles dans la communauté mondiale FabChain ou éventuellement la possibilité d'être échangés contre de la monnaie fiduciaire.
En outre, FabChain vise à émettre une série de jetons de certification ad hoc pour déterminer le niveau de compétences et de compétences des individus ou des groupes; la qualité des services, des outils et des apprentissages, ainsi que les normes de sécurité des Fab Labs; la qualité des conceptions et autres utilisations pertinentes. Enfin, FabChain prévoit également une attribution appropriée aux designers et à leurs créations.
Le modèle FabChain apporte des contributions significatives au développement de systèmes de responsabilisation aptes à une production durable et inclusive. Il illustre l'utilisation de la technologie du grand livre distribué pour coordonner simultanément la production sociale au niveau mondial, tout en contrôlant les flux de matières locaux. Cela peut être crucial, en particulier au niveau de la ville, où se concentre une capacité critique d'activités économiques circulaires, en raison de la densité de population, de l'existence de compétences et de capacités diverses et de matériaux disponibles pour la réutilisation. Il a déjà été soutenu (Bauwens & Niaros, 2018) que les villes offrent un contexte favorable aux transitions communes.
Terra0: Donner une agence DAO aux ressources naturelles
Terra0 vise à créer une capacité pour les systèmes de ressources naturelles, comme les forêts, de développer leur propre agence technologique et juridique, en devenant des DAO. Plusieurs pays, tels que l'Équateur, la Bolivie et la Nouvelle-Zélande, ont commencé à donner un statut de personnalité juridique aux forêts et aux rivières. Mais jusqu'à présent, les organisations humaines doivent saisir les tribunaux afin de réaliser cette agence au nom des entités de ressources naturelles. Le projet terra0 va encore plus loin, en reliant l'entité ressource à des capteurs, des portefeuilles et en en faisant un DAO qui peut initier des actions par lui-même.

Terra0 est un cadre basé sur Ethereum et vise à fournir une résilience automatisée pour les écosystèmes naturels. Il envisage la création de règles employant les DAO qui permettraient aux écosystèmes naturels, y compris les parcelles de terre ou les forêts, d'autogérer les ressources qu'ils encapsulent. Le but de terra0 est de créer des écosystèmes technologiquement augmentés qui peuvent être plus résilients, et d'acquérir une capacité d'action pour appliquer des règles prédéterminées dans les relations économiques.
L'un des premiers scénarios de terra0 envisage une forêt technologiquement augmentée qui peut calculer et réguler sa production en termes de matières premières, et en particulier de bois, mais aussi d'autres services qu'elle peut offrir aux agents humains et non humains, y compris la qualité détente pour les visiteurs, écosystème protégé pour diverses espèces et contributions à l'équilibre écologique global. Le scénario terra0 imagine un passage d'une situation où des tiers exploitent les éléments de la forêt, à une situation où la forêt est en mesure de s'engager dans des transactions et de revendiquer le contrôle de la valeur d'échange générée par ses actifs.
À cette fin, un contrat intelligent serait créé sur la blockchain Ethereum pour contrôler les entrées et les sorties de la forêt en utilisant des données provenant de sources externes (par exemple, des images satellites) ou intégrées (par exemple, des bases de données préconfigurées, des capteurs) pour déterminer le nombre, l'âge et l'état actuel des arbres. Un premier événement de crowdsale distribuerait des jetons terra0 aux actionnaires (humains) du projet, sous forme de débenture.14 Ces jetons ne sont pas transférables et représentent une part de la propriété du contrat intelligent, alors que la forêt est cédée à lui-même en échange de débentures. Cela signifie qu'au stade initial, la forêt se possède elle-même, mais qu'elle est redevable à ses actionnaires.
La forêt peut ensuite gérer l'exploitation de ses ressources grâce à un contrat intelligent distinct qui délivre des Woodtokens pour octroyer des licences pour l'exploitation de certains arbres. Le Woodtoken reflète une quantité convenue de bois conformément à des paramètres économiques et écologiques prédéterminés, tels que l'âge et la densité des arbres nécessaires à la préservation d'un certain niveau de population d'arbres ou de taux de croissance.
En utilisant les revenus de ces licences, la forêt peut racheter ses jetons terra0 en payant ses créanciers. Une fois que tous les jetons terra0 ont été échangés, la forêt est l'unique actionnaire de sa propre unité économique. Elle peut alors continuer à réguler ses ressources en maîtrisant la problématique des jetons à bois et en fonction de différents niveaux de préservation ou de besoins.
Il existe plusieurs inconvénients qui peuvent être identifiés dans le modèle terra0. Pour commencer, comme Regen Network, il se concentre sur la reconfiguration des forces du marché en monétisant certains éléments de l'écosystème naturel. De plus, à moins que les arbres ne soient capables de concevoir et de mettre en œuvre eux-mêmes les règles des contrats intelligents, ce sont toujours les humains qui ont la principale influence sur eux. À un niveau plus large, l'idée même que les forêts gagnent en agence économique est quelque peu triviale. En fait, une grande partie de la lutte dans les mouvements écologiques semble être dans la direction opposée, c'est-à-dire soulager les écosystèmes naturels des fonctions de marché, sans parler de leur permettre d'imiter les humains et de participer dans des conditions similaires.
Mais encore, terra0 reste une expérience intéressante qui tente de permettre différentes opportunités technologiques pour la gouvernance des communs. Il s'appuie sur une combinaison potentielle de technologies de télédétection, d'apprentissage automatique et de registre distribué pour développer des outils susceptibles de faciliter divers résultats dans la gestion collective des écosystèmes et des ressources naturels, éclairés par l'interaction des mailles des DAO, qui peuvent déployer certaines règles collectives. et normes.
Ostrom Contracts: une gouvernance commune pour l'évolution des contrats intelligents
Les contrats Ostrom s'appuient sur une convergence prometteuse de la conception de contrats intelligents avec les principes d'Elinor Ostrom pour une gouvernance réussie des biens communs. Il offre une trajectoire utile pour le développement de la technologie blockchain pour permettre et soutenir l'auto-gouvernance et la durabilité.
L'idée des contrats Ostrom est inspirée des travaux d'Elinor Ostrom (1990) sur la gouvernance des communs. Il s'agit de contrats intelligents alimentés par l'IA couplés à une surveillance environnementale intelligente, éclairés par les principes de conception d'Ostrom15 pour des communs réussis. Il s'appuie sur un ensemble d'opportunités, sans doute, inexploitées de contrats intelligents, qui peuvent offrir des outils accessibles pour concevoir des incitations économiques de manière peu coûteuse et évolutive, et ainsi démocratiser la conception des mécanismes de gouvernance.
Plus précisément, Ostrom Contracts envisage la possibilité de contrats intelligents pour permettre le traitement des fonctions économiques à la manière des logiciels. Cela signifie prototyper, tester et itérer sur les «économies», en intégrant différents motifs et incitations dans le code logiciel.16 De cette façon, en compilant les principes d'Ostrom dans un produit logiciel, nous fournissons des informations sur la façon de mettre en œuvre avec succès la coopération économique basée sur les communs.
Certaines interprétations possibles des principes d'Ostrom dans les fonctions liées aux contrats intelligents pourraient être les suivantes: 17 
    • Principe 1: des limites clairement définies grâce à une adhésion basée sur des jetons 
Les agents qui bénéficient des ressources partagées et en prennent soin doivent être clairement définis, de même que les limites des ressources elles-mêmes. L'adhésion numérique peut aider à déterminer des limites de groupe claires et peut être mise en œuvre en possédant simplement un jeton. Les modèles d'adhésion motivent les gens à coopérer les uns avec les autres en augmentant la confiance et en réduisant le risque d'être exploités, en particulier lorsqu'ils peuvent toujours se retirer en vendant ou en transférant leur (s) jeton (s). En ce sens, les incitations à rester dans le groupe sont liées aux droits d'accès aux ressources naturelles communes et / ou aux avantages collectifs précieux (par exemple, un marché partagé et facile d'accès, plus de pouvoir de décision, un revenu supplémentaire).
    • Principes 2 et 3: Gouvernance Blockchain pour la prise de décision collective avec les conditions locales en échec 
Une gouvernance réussie basée sur les communs nécessite la restriction des règles et des normes en termes de temps, de lieu, de technologie et / ou de quantité d'unités de ressources, en fonction des conditions biophysiques locales, y compris les ressources naturelles, la main-d'œuvre, le matériel et / ou l'argent. De plus, la majorité des personnes concernées par les règles opérationnelles peuvent participer à leur modification et à leur application. Les contrats intelligents permettent une prise de décision rapide avec de faibles frais généraux. Les membres du groupe peuvent proposer de manière interactive des lignes directrices et des actions et voter sur toutes les propositions, déterminant ainsi leurs propres règles et les adaptant rapidement. La gouvernance de la blockchain peut permettre le développement de nouvelles méthodes de prise de décision, basées sur des règles prédéfinies. Ceux-ci sont éclairés par des préoccupations locales et mondiales.
    • Principe 4: Surveillance et apprentissage intelligents des machines
Dans les systèmes autogérés, le suivi des conditions des ressources partagées et du comportement des individus est mis en œuvre soit par les membres du groupe eux-mêmes et / ou par les autorités responsables devant eux. Cependant, dans les grands écosystèmes naturels, comme les forêts tropicales amazoniennes ou le vaste paysage de la région du Sahel africain, il est presque impossible pour un groupe d'humains de surveiller en permanence une aussi grande quantité de territoire. L'automatisation évolutive peut offrir de grandes possibilités pour surveiller efficacement les biens communs plus vastes, tout en maintenant la confiance à travers les institutions collectives et la responsabilité envers les membres de la communauté. Un certain nombre de projets de recherche sur la surveillance de la faune, la planification des patrouilles et la prévision, tels que GainForest18 et The Great Elephant Census19, offrent déjà des preuves empiriques prometteuses sur la faisabilité de tels modèles.
    • Principes 5 et 6: sanctions graduées et mécanismes de résolution des conflits faciles à appliquer grâce à des enjeux croissants et un juge des contrats intelligents 
Les groupes autonomes prévoient souvent des sanctions progressives pour les contrevenants aux règles opérationnelles afin d'éviter des violations répétées des règles. Ces sanctions dépendent de la gravité et du contexte de l'infraction et sont évaluées par d'autres pairs et / ou fonctionnaires responsables devant ces pairs. Les plates-formes à faible coût pour la résolution rapide des conflits offrent efficacité et résilience. Dans le cas d'un contrat intelligent, si une violation de règle est détectée, une fonction d'auto-application peut être invoquée, ce qui peut, par exemple, soustraire des frais d'un dépôt d'un certain agent. De même, différents niveaux de sanctions peuvent être décidés soit par vote, soit automatiquement.
Pour les litiges plus complexes, un contrat intelligent peut également jouer le rôle du juge. Des jeux de défi / réponse peuvent également être mis en œuvre, où un groupe d'acteurs aura la possibilité de soumettre des preuves pour falsifier un certain ensemble de faits, et si aucune preuve convaincante n'est soumise sur une période de temps, alors la vérité peut être supposée.
    • Principes 7 et 8: reconnaissance de niveau supérieur et conception imbriquée par résistance et complexité à la censure programmable 
Pour les systèmes plus larges, les droits des roturiers à concevoir leurs propres règles de gouvernance ne devraient pas être contestés par des autorités formelles externes. De même, la fourniture, le suivi, l'application, la résolution des conflits et la gouvernance doivent être organisés en plusieurs couches imbriquées pour permettre une résilience à plus grande échelle. La nature décentralisée et auto-exécutoire des contrats intelligents basés sur la blockchain garantit formellement que les décisions, prises dans ce cadre, sont exécutées sans censure ni contrôle des autorités de niveau supérieur. En outre, les architectures de contrats intelligents peuvent être arbitrairement complexes, permettant le développement de structures de gouvernance complexes sans limites de granularité.
Les contrats Ostrom visent à encourager la coopération et l'auto-gouvernance. Les contrats intelligents servent de moyen de transaction et de gouvernance pour permettre aux gens de s'auto-organiser et de décider collectivement de questions communes. Pour cette raison, il devrait y avoir différents niveaux d'engagement pour le déploiement de contrats intelligents. Les contrats Ostrom faiblement couplés servent simplement de média pour l'auto-organisation, tandis que la communauté reste le principal agent pour faire appliquer et mettre en œuvre leurs règles de gouvernance et de sanctions. Les contrats étroitement couplés peuvent aller plus loin et appliquer automatiquement l'exécution. L'automatisation peut offrir des solutions prometteuses en transférant le niveau de confiance des utilisateurs vers le système. Cependant, les systèmes automatisés ont également de nombreuses implications potentiellement dangereuses car ils ne sont pas à l'abri des préjugés et des attaques adverses.
L'émergence de la gouvernance de la blockchain a inspiré un large éventail d'expérimentations pour mettre en œuvre des affaires politiques et économiques complexes à travers le code. Il y a des revendications sur la possibilité de tester et de mettre en œuvre différents systèmes et d'appliquer des méthodes pour évaluer, réitérer et potentiellement améliorer différentes variations des résultats économiques. Par exemple, P2P Models20 est un autre projet de recherche qui s'appuie sur le potentiel des plateformes d'économie collaborative exploitant la technologie blockchain. S'appuyant sur les principaux résultats du projet P2P Value 21, il envisage une combinaison similaire de règles fondées sur les communs pour une nouvelle génération de communautés d'économie collaborative autonomes et plus durables sur le plan économique. Enfin, l'Intelligence Artificielle, dont les formes sont déjà déployées dans nombre de nos applications quotidiennes, peuvent également être mis en œuvre pour augmenter les contrats intelligents. De telles itérations du développement de ces technologies émergentes comportent de nombreuses promesses pour fournir de meilleures informations sur l'alignement potentiel de l'intérêt personnel humain avec le bien commun.
